### PR TITLE
Modify ProfitLossInteractor, but it result to modify almost everything

### PR DESCRIPTION
**Pull request by Mind-MNK**
I'm so sorry for pushing it quite late. I didn't expect to modify almost every file after editing Interactor, which took more time than thought. I think everything should work now, there is an issue with creating a mock portfolio in the tests, so I haven’t been able to fully test it yet. However, since I understand everyone has been waiting, I decided to push my changes as they are.

Additionally, I noticed that the LoggedInView modification of my UI part and SetField part that I implemented on Monday seems to be lost while solving conflict. For my panel at the bottom, I already added it back, but for SetField I'm not sure whether someone meant to remove it because it doesn't need anymore or it just lost too, so I added it back with commenting it out for now. If it is the latter case which is just lost out, please remove the comment.

Thank you so much!

### CODE REVIEW

**Review by amvipat — CHANGES_REQUESTED** [review]
Use Maya's version of logged in State: this is what we have now:

 public Map<String, Double> getStockProfitLoss() {
        return stockProfitLoss;
    }

**Review by amvipat — CHANGES_REQUESTED** [review]
Have 1 method called execute in the interactor file. Calculate total profit and profit for each stock in this one method.

**Review by amvipat — APPROVED** [review]
Have 1 method in the presenter - called success

in this method update 2 variables in logged in state. Total profit loss and the private Map<String, Double> stockProfitLoss;

**Review by amvipat — CHANGES_REQUESTED** [review]
In your output data object, you're missing data. You need the profit loss of each stock in this one object. You're only tracking 1 stock right now

**Review by amvipat — CHANGES_REQUESTED** [review]
Input Boundary should only have 1 method - called execute. This is to be consistent across all interactors

**Comment by Mind-MNK** [comment]
@amvipat I’ve made some adjustments and hope everything works now. I tried running the app builder, and there don’t seem to be any clashes. However, my test is still failing.

I suspect the issue is from my test somehow using the prices from the portfolio as the current prices instead of the mock prices, but I can’t figure out how to fix it. If you could help point out anything I might have done wrong or missed, I would really appreciate it. @phuonganhdangamy, if you have some time, could you also take a look at the test? I think it might help me better understand what I’m doing wrong.

I’ve pushed the changes first so you can continue connecting the functional parts if they’re working properly. Thanks you so much!

**Review by phuonganhdangamy — APPROVED** [review]

**Review by phuonganhdangamy — APPROVED** [review]

**Pull request merged**
